agent:
  reward_scaling_factor: 10
  noise_params:
    type: ornstein_uhlenbeck
    stddev: 0.1
    ou_damping: 0.1
  policy_model:
    type: type2

replay_buffer:
  alpha: 0.8
  beta: 0.6

environment:
  env_id: BipedalWalker-v3

algorithm:
  training_steps: 30000
