agent:
  class: TD3Agent
  gamma: 0.995
  critic_learning_rate: 2e-3
  actor_learning_rate: 1e-4
  policy_model: type1
  critic_model: type1
  noise_stddev: 0.2
  reward_scaling_factor: 10

replay_buffer:
  class: ReplayBuffer
  size: 10000

environment:
  env_id: BipedalWalker-v3
  seed: 0
  monitor: False

algorithm:
  class: OffPolicyAlgorithm
  training_steps: 30000
  evaluate_every: 10
  train_every: 128
  batch_size: 128
  make_critic_checkpoint: False
  restore_from_checkpoint: False
  return_viewer: False
