agent:
  reward_scaling_factor: 40
  noise_params:
    type: ornstein_uhlenbeck
    stddev: 0.1
    ou_damping: 0.04
  gamma: 0.95





environment:
  env_id: MountainCarContinuous-v0

algorithm:
  training_steps: 2000
